### ISSUE TITLE
when i run files2rouge summaries.txt references.txt i get this. My summaries.txt and references.txt have line by line entries

### ISSUE THREAD

**Issue by vishrutkohli** [pltrdy/files2rouge#13]
```
Preparing documents...
Running ROUGE...
Cannot open exception db file for reading: yes/data/WordNet-2.0.exc.db
Traceback (most recent call last):
  File "/Users/vishrutkohli/Desktop/keras-text-summarization/demo/files2rouge/env3/bin/files2rouge", line 11, in <module>
    load_entry_point('files2rouge==2.0.0', 'console_scripts', 'files2rouge')()
  File "/Users/vishrutkohli/Desktop/keras-text-summarization/demo/files2rouge/env3/lib/python3.6/site-packages/files2rouge-2.0.0-py3.6.egg/files2rouge/files2rouge.py", line 82, in main
    output = r.convert_and_evaluate(rouge_args=rouge_args_str)
  File "/Users/vishrutkohli/Desktop/keras-text-summarization/demo/files2rouge/env3/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 367, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/Users/vishrutkohli/Desktop/keras-text-summarization/demo/files2rouge/env3/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 342, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "/Users/vishrutkohli/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/vishrutkohli/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['yes/ROUGE-1.5.5.pl', '-e', 'yes/data', '-c', '95', '-r', '1000', '-n', '2', '-a', '-m', '/var/folders/3h/7x3f6sqd1276lk8pz98k5k300000gn/T/tmpsvwqq4ob/rouge_conf.xml']' returned non-zero exit status 79.
```

**Comment by pltrdy** [comment]
You may need to check if the file is present, and if you have sufficient privilege with `ls -l yes/data/WordNet-2.0.exc.db`
