### ISSUE TITLE
error

### ISSUE THREAD

**Issue by baongocst96** [pltrdy/files2rouge#14]
PS D:\LuanVan\Rouge\files2rouge> files2rouge summaries.txt references.txt
Preparing documents...
Running ROUGE...
Traceback (most recent call last):
  File "N:\python_86\Scripts\files2rouge-script.py", line 11, in <module>
    load_entry_point('files2rouge==2.0.0', 'console_scripts', 'files2rouge')()
  File "N:\python_86\lib\site-packages\files2rouge-2.0.0-py3.6.egg\files2rouge\files2rouge.py", line 82, in main
    output = r.convert_and_evaluate(rouge_args=rouge_args_str)
  File "N:\python_86\lib\site-packages\pyrouge\Rouge155.py", line 367, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "N:\python_86\lib\site-packages\pyrouge\Rouge155.py", line 342, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "N:\python_86\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "N:\python_86\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "N:\python_86\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "N:\python_86\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by pltrdy** [comment]
Windows isn't supported for now. I do not plan to personally investigate on this, contributions are welcome!

**Comment by udnet96** [comment]
Open C:\Anaconda\envs\py35\Lib\site-packages\pyrouge\Rouge155.py (or wherever you installed pyrouge), go to the function def evaluate(self, system_id=1, rouge_args=None) (it's at line 319 at the time I am writing this answer), and add command.insert(0, 'perl ') right before self.log.info("Running ROUGE with command {}".format(" ".join(command))). (If you don't do it, you'll get OSError: [WinError 193] %1 is not a valid Win32 application, which is the same error message as what you would get for if you don't do some of the previous steps).
