### ISSUE TITLE
SyntaxError: invalid syntax for print(*args, **kwargs)

### ISSUE THREAD

**Issue by bilymufac** [pltrdy/files2rouge#15]
I've got an error as a traceback below:

```
Traceback (most recent call last):
  File "setup_rouge.py", line 7, in <module>
    from files2rouge import settings
  File "/home/cerdas/files2rouge/files2rouge/__init__.py", line 2, in <module>
    from files2rouge.files2rouge import main
  File "/home/cerdas/files2rouge/files2rouge/files2rouge.py", line 17, in <module>
    from files2rouge import utils
  File "/home/cerdas/files2rouge/files2rouge/utils.py", line 14
    print(*args, **kwargs)
          ^
SyntaxError: invalid syntax
```

the error occured when i'm trying to run this code:

```
def tee(saveto, *args, **kwargs):
    """Mimic the tee command, write on both stdout and file
    """
    print(*args, **kwargs)
    if saveto is not None:
        print(file=saveto, *args, **kwargs)
```

i've read and searching for similar problem, but i still can't solved the error. Thanks

**Comment by wanghm92** [comment]
add the line `from __future__ import print_function` at the very beginning fix the problem
