### ISSUE TITLE
SyntaxError: invalid syntax for print(file=saveto, *args, **kwargs)

### ISSUE THREAD

**Issue by bilymufac** [pltrdy/files2rouge#16]
i've got the error as the traceback below, when I try to run the command `python setup_rouge.py`

```
Traceback (most recent call last):
  File "setup_rouge.py", line 7, in <module>
    from files2rouge import settings
  File "/home/cerdas/files2rouge/files2rouge/__init__.py", line 2, in <module>
    from files2rouge.files2rouge import main
  File "/home/cerdas/files2rouge/files2rouge/files2rouge.py", line 17, in <module>
    from files2rouge import utils
  File "/home/cerdas/files2rouge/files2rouge/utils.py", line 16
    print(file=saveto, *args, **kwargs)
              ^
SyntaxError: invalid syntax
```
I have no idea whats wrong with the code, thanks.

**Comment by pltrdy** [comment]
1. Could you specify which python version you're running? (it's working on my `3.6.1`)
2. You could try with `print(*args, file=saveto, **kwargs)`, I guess using keyword (i.e. `file=`) before positional arguments (i.e. `*args`) may cause trouble.

**Comment by bilymufac** [comment]
Thanks, I change the python version to 3.x and its working properly.
