### ISSUE TITLE
Getting error python setup_rouge.py

### ISSUE THREAD

**Issue by sajastu** [pltrdy/files2rouge#19]
Hey,

Just aimed to run this command: `python setup_rouge.py`, but encountering the following error:

> Traceback (most recent call last):
  File "setup_rouge.py", line 7, in <module>
    from files2rouge import settings
  File "/Users/ss4164/PycharmProjects/testProject/files2rouge/files2rouge/__init__.py", line 2, in <module>
    from files2rouge.files2rouge import main
  File "/Users/ss4164/PycharmProjects/testProject/files2rouge/files2rouge/files2rouge.py", line 17, in <module>
    from files2rouge import utils
  File "/Users/ss4164/PycharmProjects/testProject/files2rouge/files2rouge/utils.py", line 14
    print(*args, **kwargs)
          ^

Is this a common error? How would you solve it?

Thanks,

**Comment by pltrdy** [comment]
Can you pull the patch for this: 
```
git checkout -b python2_tee
git pull origin python2_tee
```
then try again?

**Comment by pltrdy** [comment]
It seems to be ok. Do not hesitate to re-open otherwise.
