### ISSUE TITLE
Exception: Could not find any model summaries for the system summary with ID 1000. Specified model filename pattern was: m.[A-Z].#ID#.txt

### ISSUE THREAD

**Issue by jufengada** [pltrdy/files2rouge#22]
Hey,

Just aimed to run this command: python files2rouge.py, but encountering the following error:
```
Preparing documents...
Running ROUGE...
Traceback (most recent call last):
  File "/anaconda/bin/files2rouge", line 11, in <module>
    load_entry_point('files2rouge==2.0.0', 'console_scripts', 'files2rouge')()
  File "/anaconda/lib/python3.5/site-packages/files2rouge-2.0.0-py3.5.egg/files2rouge/files2rouge.py", line 82, in main
    output = r.convert_and_evaluate(rouge_args=rouge_args_str)
  File "/anaconda/lib/python3.5/site-packages/pyrouge/Rouge155.py", line 367, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/anaconda/lib/python3.5/site-packages/pyrouge/Rouge155.py", line 334, in evaluate
    self.write_config(system_id=system_id)
  File "/anaconda/lib/python3.5/site-packages/pyrouge/Rouge155.py", line 318, in write_config
    self._config_file, system_id)
  File "/anaconda/lib/python3.5/site-packages/pyrouge/Rouge155.py", line 273, in write_config_static
    id, model_dir, model_filename_pattern)
  File "/anaconda/lib/python3.5/site-packages/pyrouge/Rouge155.py", line 506, in __get_model_filenames_for_id
    "{}".format(id, model_filenames_pattern))
Exception: Could not find any model summaries for the system summary with ID 1000. Specified model filename pattern was: m.[A-Z].#ID#.txt
```
Is this a common error? How would you solve it?

Thanks,

**Comment by pltrdy** [comment]
The command isn't supposed to work anyway. You should pass it arguments.

**Comment by jufengada** [comment]
Sorry, I still don't understand. How should I pass it argument？

**Comment by jufengada** [comment]
Sorry, I still don't understand. How should I pass it argument？

**Comment by pltrdy** [comment]
you should directly pass file paths are positional arguments i.e.
```
files2rouge my_summaries.txt my_references.txt 
```
