### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'stemming'

### ISSUE THREAD

**Issue by vighneshck** [pltrdy/files2rouge#45]
Hi,
On running the command: `files2rouge reference.txt summary.txt`

I get the following error:
`Preparing documents... 0 line(s) ignored
Running ROUGE...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/files2rouge", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/files2rouge/files2rouge.py", line 107, in main
    run(args.summary,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/files2rouge/files2rouge.py", line 53, in run
    r = pyrouge.Rouge155(rouge_dir=os.path.dirname(s.data['ROUGE_path']),
TypeError: __init__() got an unexpected keyword argument 'stemming'`

P.S.:

1. I have installed Python3.8.7 and pip21.0.1
2. I get the same error even after adding the `-nm` flag to the above command.

**Comment by pltrdy** [comment]
We use a custom version of `pyrouge` that you should install with `pip install -U git+https://github.com/pltrdy/pyrouge`. This should solve the problem
