### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/Bwwhst28Y/anaconda3/envs/pytorch/lib/python3.6/site-packages/files2rouge-2.1.0-py3.6.egg/files2rouge/ROUGE-1.5.5.pl'

### ISSUE THREAD

**Issue by 1029694141** [pltrdy/files2rouge#47]
when i run files2rouge /home/Bwwhst28Y/MASS-summarization/tgt.txt /home/Bwwhst28Y/MASS-summarization/hypo.txt
then the error is 
PermissionError: [Errno 13] Permission denied: '/home/Bwwhst28Y/anaconda3/envs/pytorch/lib/python3.6/site-packages/files2rouge-2.1.0-py3.6.egg/files2rouge/ROUGE-1.5.5.pl'

**Comment by 1029694141** [comment]
Here is the Traceback
 Running ROUGE...
Traceback (most recent call last):
  File "/home/Bwwhst28Y/anaconda3/bin/files2rouge", line 33, in <module>
    sys.exit(load_entry_point('files2rouge==2.1.0', 'console_scripts', 'files2rouge')())
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/site-packages/files2rouge-2.1.0-py3.8.egg/files2rouge/files2rouge.py", line 110, in main
    run(args.summary,
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/site-packages/files2rouge-2.1.0-py3.8.egg/files2rouge/files2rouge.py", line 75, in run
    output = r.convert_and_evaluate(rouge_args=rouge_args_str)
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/site-packages/pyrouge/Rouge155.py", line 368, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/site-packages/pyrouge/Rouge155.py", line 343, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/Bwwhst28Y/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/Bwwhst28Y/anaconda3/envs/pytorch/lib/python3.6/site-packages/files2rouge-2.1.0-py3.6.egg/files2rouge/ROUGE-1.5.5.pl'

**Comment by pltrdy** [comment]
Can you check file permission ? i.e. `ls -l /home/Bwwhst28Y/anaconda3/envs/pytorch/lib/python3.6/site-packages/files2rouge-2.1.0-py3.6.egg/files2rouge/ROUGE-1.5.5.pl`

**Comment by 1029694141** [comment]
the result is:
-rw-rw-r-- 1 Bwwhst28Y Bwwhst28Y 103888 4月  24 15:44 /home/Bwwhst28Y/anaconda3/envs/pytorch/lib/python3.6/site-packages/files2rouge-2.1.0-py3.6.egg/files2rouge/ROUGE-1.5.5.pl

**Comment by 1029694141** [comment]
I initialized my anaconda environment then the problem will be deal ，thanks very much！
