### ISSUE TITLE
Cannot open exception db file for reading

### ISSUE THREAD

**Issue by DaisyTung** [pltrdy/files2rouge#48]
Here is the error message:
------------------------------------------------------------------------------------------
```
Preparing documents... 9 line(s) ignored
Running ROUGE...
Cannot open exception db file for reading: /Users/dongzixuan/.files2rouge/data/WordNet-2.0.exc.db
Traceback (most recent call last):
  File "/Users/dongzixuan/files2rouge/files2rouge/files2rouge.py", line 122, in <module>
    main()
  File "/Users/dongzixuan/files2rouge/files2rouge/files2rouge.py", line 110, in main
    run(args.summary,
  File "/Users/dongzixuan/files2rouge/files2rouge/files2rouge.py", line 75, in run
    output = r.convert_and_evaluate(rouge_args=rouge_args_str)
  File "/usr/local/lib/python3.9/site-packages/pyrouge/Rouge155.py", line 368, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/usr/local/lib/python3.9/site-packages/pyrouge/Rouge155.py", line 343, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/dongzixuan/.files2rouge/ROUGE-1.5.5.pl', '-e', '/Users/dongzixuan/.files2rouge/data', '-c', '95', '-r', '1000', '-n', '2', '-a', '-m', '/var/folders/9_/m35zxf157c190g94387p8yzw0000gn/T/tmp9ha1v797/rouge_conf.xml']' returned non-zero exit status 79.
```
------------------------------------------------------------------------------------------

I have tried 
`rm \RELEASE-1.5.5\data\WordNet-2.0.exc.db`
and 
```
cd RELEASE-1.5.5\data\
perl WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db

```
but it still show same messeage.
I have really no idea how to fix it, please help me!
And I operate it on MacOS.

THANK YOU SOOOO MUCH!!

**Comment by pltrdy** [comment]
Hi, sorry for the late reply.

However, it seem more like a permission issue. 
Can you check permissions (e.g. `ls -l /Users/dongzixuan/.files2rouge/data/WordNet-2.0.exc.db`) or explicitely set read permission ? `chmod +rx /Users/dongzixuan/.files2rouge/data/WordNet-2.0.exc.db`
