### ISSUE TITLE
Cannot open exception db file for reading, even with read permission

### ISSUE THREAD

**Issue by huyiwen** [pltrdy/files2rouge#56]
Hi, I have encountered the same issue as #48 but I failed to fix it by giving the db file permission:

```
l /Users/huyiwen/.files2rouge/data/WordNet-2.0.exc.db
.rwxrwxrwx 12k huyiwen  6 Jul 21:43 /Users/huyiwen/.files2rouge/data/WordNet-2.0.exc.db
```

I'm working on `macOS 12.4` and `Python 3.8.12`. I installed the module under the instruction of README. The error occurs both in command line and python script:

```
Preparing documents... 0 line(s) ignored
Running ROUGE...
Cannot open exception db file for reading: /Users/huyiwen/.files2rouge/data/WordNet-2.0.exc.db
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/TextBox/bin/files2rouge", line 33, in <module>
    sys.exit(load_entry_point('files2rouge==2.1.0', 'console_scripts', 'files2rouge')())
  File "/usr/local/Caskroom/miniconda/base/envs/TextBox/lib/python3.8/site-packages/files2rouge-2.1.0-py3.8.egg/files2rouge/files2rouge.py", line 131, in main
    run(args.summary,
  File "/usr/local/Caskroom/miniconda/base/envs/TextBox/lib/python3.8/site-packages/files2rouge-2.1.0-py3.8.egg/files2rouge/files2rouge.py", line 92, in run
    output = r.convert_and_evaluate(rouge_args=rouge_args_str)
  File "/usr/local/Caskroom/miniconda/base/envs/TextBox/lib/python3.8/site-packages/pyrouge/Rouge155.py", line 368, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/usr/local/Caskroom/miniconda/base/envs/TextBox/lib/python3.8/site-packages/pyrouge/Rouge155.py", line 343, in evaluate
    rouge_output = check_output(command, env=env).decode("UTF-8")
  File "/usr/local/Caskroom/miniconda/base/envs/TextBox/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Caskroom/miniconda/base/envs/TextBox/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/huyiwen/.files2rouge/ROUGE-1.5.5.pl', '-e', '/Users/huyiwen/.files2rouge/data', '-c', '95', '-r', '1000', '-n', '2', '-a', '-m', '/var/folders/j8/sbwvtz_j2_s7mlsj4z3zbb7r0000gn/T/tmptncmkl1e/rouge_conf.xml']' returned non-zero exit status 79.
```

Thanks a lot for your help!

**Comment by huyiwen** [comment]
I found solution here: https://github.com/masters-info-nantes/ter-resume-auto/blob/master/README.md
